<?php

/**
 * @file
 * Hello module.
 */

use \Drupal\affiliate_tracking\AffiliateTrackingController;

function affiliate_tracking_node_view($node, $view_mode, $langcode) {
	$node['#cache']['max-age'] = 0;
	if (isset($_REQUEST['affiliate'])) {

		$existing_code = AffiliateTrackingController::findTrackingCode($_REQUEST['affiliate']);
		//print_r($existing_code);
	//	if ($exiting_code != null) {
			$return = AffiliateTrackingController::addTrackingHit($existing_code->affiliate_id, "hit", "anonymous");
			echo $return;
	//	}
	}
}

function affiliate_tracking_element_info_alter(array &$types) {
	if (isset($types['toolbar'])) {
		$types['toolbar']['#attached']['library'][] = 'affiliate_tracking/affiliate_tracking_private';
	}

	if (isset($_REQUEST['affiliate'])) {
	//if (isset($types['toolbar'])) {
		$types['toolbar']['#attached']['library'][] = 'affiliate_tracking/affiliate_tracking_public';
//	}
	}
}
